---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:65FKwomAy6k_A3Ki6kvMiw@db:5432/postgres
      NODE_ENV: production
  app:
    extends:
      service: common
    links:
    - db
    environment:
      POSTGRES_PASSWORD: 65FKwomAy6k_A3Ki6kvMiw
    ports:
    - 1337:1337
    command: node app.js --prod
  db:
    image: postgres
